#!/bin/sh
#
# Copyright (c) 2016 Hannes von Haugwitz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

. "${HOME}/.config/i3blocks/colours"

CORE_RAW=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp1_input)
CORE_TEMP=$(( CORE_RAW/1000 ))

echo "${CORE_TEMP}℃"
echo "${CORE_TEMP}℃"
if [ "${CORE_TEMP}" -ge "80" ] ; then
    echo
    exit 33
elif [ "${CORE_TEMP}" -ge "70" ] ; then
    echo "${COLOUR_RED}"
elif [ "${CORE_TEMP}" -ge "50" ] ; then
    echo "${COLOUR_YELLOW}"
else
    echo "${COLOUR_GREEN}"
fi

exit 0
