#!/bin/sh
#
# Copyright (c) 2016 Hannes von Haugwitz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

. "${HOME}/.config/i3blocks/colours"

IPV6=$(ip -6 addr show | awk '/scope global/ { print $2 }' | head -n1 | cut -d / -f 1)
IPV6_COLOUR=${COLOUR_GREEN}

if [ -z "${IPV6}" ] ; then
    IPV6="no IPv6"
    IPV6_COLOUR=${COLOUR_RED}
fi

# highlight disabled IPv6 privacy extensions
if echo "${IPV6}" | grep -Eq "[0-9a-f]{1,4}(:[0-9a-f]{1,4}){4}:[0-9a-f]{0,2}ff:fe[0-9a-f]{2}:[0-9a-f]{4}"; then
    IPV6_COLOUR=${COLOUR_ORANGE}
fi

echo "${IPV6}"
echo "${IPV6}"
echo "${IPV6_COLOUR}"

exit 0
